import React, { useMemo, useState } from 'react'
import { Image, Text, TouchableOpacity, View } from 'react-native'
import moneyFormat from '@/utils/moneyFormat'
import { icons } from '@/constants/icons'

type ReceiptStatus = 'successful' | 'pending' | 'failed'

type ReceiptMeta = {
  channel?: string
  beneficiary?: string
  bankName?: string
  accountNumber?: string
  providerReference?: string
  sessionId?: string
  narration?: string
  remark?: string
}

type BankReceiptCardProps = {
  title: string
  createdAt: string
  status: ReceiptStatus | string
  amount: number
  currency: string
  reference: string
  fees?: number
  meta?: ReceiptMeta
}

const normalizeStatus = (statusRaw: string) => {
  const s = String(statusRaw || 'pending').toLowerCase()
  if (s.includes('success') || s.includes('complete') || s.includes('approved') || s.includes('paid'))
    return 'successful'
  if (s.includes('fail') || s.includes('declin') || s.includes('revers') || s.includes('error'))
    return 'failed'
  return 'pending'
}

const statusPill = (statusRaw: string) => {
  const status = normalizeStatus(statusRaw)
  if (status === 'successful') {
    return { label: 'Success', bg: 'bg-emerald-500/15', border: 'border-emerald-500/30', text: 'text-emerald-300' }
  }
  if (status === 'failed') {
    return { label: 'Failed', bg: 'bg-red-500/15', border: 'border-red-500/30', text: 'text-red-300' }
  }
  return { label: 'Pending', bg: 'bg-amber-500/15', border: 'border-amber-500/30', text: 'text-amber-300' }
}

const clean = (value?: any) => {
  const v = String(value ?? '').trim()
  if (!v) return ''
  const low = v.toLowerCase()
  if (low === 'undefined' || low === 'null') return ''
  return v
}

const maskAccountNumber = (value?: string) => {
  const s = String(value || '').replace(/\s+/g, '')
  if (!s) return ''
  if (s.length <= 4) return `****${s}`
  return `${'*'.repeat(Math.max(0, s.length - 4))}${s.slice(-4)}`
}

const Divider = () => <View className="h-[1px] bg-gray-800 my-4" />

const Row = ({ label, value, mono }: { label: string; value?: string; mono?: boolean }) => {
  const v = clean(value)
  if (!v) return null
  return (
    <View className="flex-row justify-between items-start py-1.5">
      <Text className="text-gray-500 text-[12px]">{label}</Text>
      <Text className={`${mono ? 'font-mono' : ''} text-gray-200 text-[12px] max-w-[62%] text-right`}>
        {v}
      </Text>
    </View>
  )
}

const BankReceiptCard = ({
  title,
  createdAt,
  status,
  amount,
  currency,
  reference,
  fees,
  meta,
}: BankReceiptCardProps) => {
  const [showAdvanced, setShowAdvanced] = useState(false)

  const pill = useMemo(() => statusPill(String(status)), [status])

  const safeCurrency = String(currency || 'NGN')
  const safeAmount = Number.isFinite(Number(amount)) ? Number(amount) : 0

  const safeFees = typeof fees === 'number' && Number.isFinite(fees) && fees > 0 ? Number(fees) : undefined
  const net = typeof safeFees === 'number' ? Math.max(0, safeAmount - safeFees) : undefined

  const channel = clean(meta?.channel)
  const providerRef = clean(meta?.providerReference)
  const sessionId = clean(meta?.sessionId)

  const beneficiary = clean(meta?.beneficiary)
  const bankName = clean(meta?.bankName)
  const accountNumberMasked = maskAccountNumber(clean(meta?.accountNumber))

  const narration = clean(meta?.narration) || clean(meta?.remark)

  const displayTitle = clean(title) || 'Receipt'
  const displayTime = clean(createdAt) || '--'
  const receiptNo = clean(reference) || '--'

  return (
    <View className="bg-gray-950 border border-gray-800 rounded-2xl p-5">
      {/* Header */}
      <View className="flex-row items-start justify-between">
        <View className="flex-1 pr-3">
          <View className="flex-row items-center">
            <Image source={icons.appLogoClear} resizeMode="contain" style={{ width: 105, height: 22 }} />
            <Text className="text-gray-300 text-[12px] font-semibold ml-2">BitBridge</Text>
          </View>

          <Text className="text-white text-[18px] font-semibold mt-3">{displayTitle}</Text>
          <Text className="text-gray-400 text-[12px] mt-1">{displayTime}</Text>

          <Text className="text-gray-500 text-[11px] mt-2">Generated by BitBridge</Text>
        </View>

        <View className={`px-3 py-1.5 rounded-full border ${pill.bg} ${pill.border}`}>
          <Text className={`${pill.text} text-[11px] font-semibold`}>{pill.label}</Text>
        </View>
      </View>

      {/* Amount */}
      <View className="mt-5">
        <Text className="text-white text-3xl font-semibold">{moneyFormat(safeAmount, safeCurrency)}</Text>

        {typeof safeFees === 'number' ? (
          <Text className="text-gray-400 text-[12px] mt-1">
            Fees: {moneyFormat(safeFees, safeCurrency)}
            {typeof net === 'number' ? `  •  Net: ${moneyFormat(net, safeCurrency)}` : ''}
          </Text>
        ) : (
          <Text className="text-gray-500 text-[12px] mt-1">Fees may apply depending on channel.</Text>
        )}
      </View>

      <Divider />

      {/* Summary */}
      <Text className="text-gray-400 text-[11px] uppercase tracking-widest mb-2">Summary</Text>
      <Row label="Receipt No" value={receiptNo} mono />
      <Row label="Channel" value={channel} />
      <Row label="Narration" value={narration} />

      {(beneficiary || bankName || accountNumberMasked) ? (
        <>
          <Divider />
          <Text className="text-gray-400 text-[11px] uppercase tracking-widest mb-2">Beneficiary</Text>
          <Row label="Name" value={beneficiary} />
          <Row label="Bank" value={bankName} />
          <Row label="Account" value={accountNumberMasked} mono />
        </>
      ) : null}

      <Divider />

      {/* Advanced */}
      <TouchableOpacity
        onPress={() => setShowAdvanced((v) => !v)}
        className="bg-gray-900 border border-gray-800 px-4 py-3 rounded-xl"
        accessibilityRole="button"
      >
        <Text className="text-gray-200 text-sm font-semibold">{showAdvanced ? 'Hide details' : 'Show details'}</Text>
        <Text className="text-gray-500 text-[11px] mt-1">Provider references and internal identifiers.</Text>
      </TouchableOpacity>

      {showAdvanced ? (
        <View className="mt-3 bg-gray-900 border border-gray-800 rounded-xl p-4">
          <Text className="text-gray-400 text-[11px] uppercase tracking-widest mb-2">Identifiers</Text>
          <Row label="Provider reference" value={providerRef} mono />
          <Row label="Session ID" value={sessionId} mono />
        </View>
      ) : null}

      <View className="mt-4 pt-4 border-t border-gray-800">
        <Text className="text-gray-500 text-[11px]">
          Keep this receipt for your records. For assistance, share your Receipt No with support.
        </Text>
      </View>
    </View>
  )
}

export default BankReceiptCard
